apiVersion: "v1"
kind: "Service"
metadata: 
  name: "order"
  labels: 
    app: "order"
  namespace: ab-test    
spec: 
  ports: 
    - 
      port: 80
      targetPort: 80
  selector: 
    app: "order"
