apiVersion: "v1"
kind: "Service"
metadata: 
  name: "order"
  labels: 
    app: "order"
  namespace: ab-test    
spec: 
  ports: 
    - 
      port: 80
      targetPort: 80
  selector: 
    app: "order"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ab-test-gateway
  namespace: ab-test
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ab-test-path-routing
  namespace: ab-test  
spec:
  hosts:
  - "*"
  gateways:
  - ab-test-gateway
  http:
  - match:
    - uri:
        prefix: /order
    route:
    - destination:
        host: order
        port:
          number: 80
